kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: gluu-config
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/opt"
          name: task-pv-storage

