apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "gluu.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.config.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "gluu.config.fullname" . }}
  annotations:
    "helm.sh/hook": post-delete
