apiVersion: v1
kind: Service
metadata:
{{- if .Values.oxauth.service.annotations }}
  annotations:
{{ toYaml .Values.oxauth.service.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "gluu.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.oxauth.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.oxauth.service.labels }}
{{ toYaml .Values.oxauth.service.labels | indent 4}}
{{- end }}
  name: {{ template "gluu.oxauth.fullname" . }}
spec:
{{- if .Values.oxauth.service.clusterIP }}
  clusterIP: {{ .Values.oxauth.service.clusterIP }}
{{- end }}
  ports:
    - name: oxauth
      port: {{ .Values.oxauth.service.servicePort }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "gluu.name" . }}
    component: "{{ .Values.oxauth.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.oxauth.service.type }}"
