apiVersion: v1
kind: Service
metadata:
{{- if .Values.oxpassport.service.annotations }}
  annotations:
{{ toYaml .Values.oxpassport.service.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "gluu.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.oxpassport.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.oxpassport.service.labels }}
{{ toYaml .Values.oxpassport.service.labels | indent 4}}
{{- end }}
  name: {{ template "gluu.oxpassport.fullname" . }}
spec:
{{- if .Values.oxpassport.service.clusterIP }}
  clusterIP: {{ .Values.oxpassport.service.clusterIP }}
{{- end }}
  ports:
    - name: oxpassport
      port: {{ .Values.oxpassport.service.servicePort }}
      protocol: TCP
      targetPort: 8090
  selector:
    app: {{ template "gluu.name" . }}
    component: "{{ .Values.oxpassport.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.oxpassport.service.type }}"
